---
title: "Exam 1 -Makeup"
format: pdf
editor: visual
---

\thispagestyle{empty}


*Name:*

*Notice: Calculators are not allowed. *

---

## Some formulas:

- The derivative of $f(x)$ is defined by the formula:
$$
f'(x) = \lim_{h \to 0} \frac{f(x+h)-f(x)}{h}
$$
\


- An equation of the tangent line at $x = a$ is
$$
y - f(a) = f'(a)(x-a)
$$

---
### Problem 1. (5 points each)

Find the following limits.

$$\lim_{x \to 2} \frac{x^2 - 4x + 4}{x^2 +5x + 1}$$

\
\
\
\


\thispagestyle{empty}

$$\lim_{x \to 2} \frac{x^2 - 3x + 2}{x^2 -6x + 8}$$

\
\
\
\
\


$$\lim_{x \to \infty} \frac{2x^6 +4x^4 + 3x^3}{7x^5 + 2024}$$

\
\
\
\
\




$$\lim_{x \to \infty} \frac{-2x^5 +4x + 3}{3x^{13} +5x + 6}$$

\
\
\
\
\


$$\lim_{x \to \infty} \frac{x+1}{x^3 +5x + 6}$$

\
\
\
\
\
\thispagestyle{empty}

$$\lim_{x \to 2} \frac{\sin 10x }{\sin 5x}$$

\
\
\
\
\


$$\lim_{x \to 0} \frac{\sin 8x }{\sin 4x}$$

\
\
\
\
\


$$\lim_{x \to 0} \frac{2x^3 + x ^2+ 3\sin x }{3x^3 + 3\sin 5x}$$

\
\
\
\
\


### Problem 2 (5 points each)

Find values of $x$, if any, at which the function is not continuous.

a.  $f(x) = 3x^2 + \frac{1}{x-1} + 2024x +1$

\
\
\
\
\

\thispagestyle{empty}

b.  $f(x) = x^2 + \frac{3}{(x - 2)(x-3)(x-4)} + 2024$

\
\
\
\
\


c.  $f(x) = \frac{3}{x + 1} + \frac{x-1}{x^2 + 7x + 6}$

\
\
\
\
\


### Problem 3. (5 points each)

Find a value of the constant $k$, if possible, that will make the function continuous everywhere.

a.  

    \begin{align*}
    f(x) =
     \left\{\begin{array}{lr}
       x^2, & x \le 2 \\
       x^2 - 3kx+1, & x > 2  
    \end{array}\right.
    \end{align*}

\
\
\
\

\
\
\
\

\thispagestyle{empty}

b.  

    \begin{align*}
    f(x) =
     \left\{\begin{array}{lr}
       3x^2 + 4x + 16, & x \le 0 \\
      - 9x + k^2, & x > 0
    \end{array}\right.
    \end{align*}

\
\
\
\

\
\
\
\

\thispagestyle{empty}

### Problem 4. (17.5 points each)

a.  Use the definition of derivatives to find $f'(x)$, and then find the tangent line to the graph of $y = f(x)$ at $x = 3$

$$
f(x) = -5x^2 + 6x + 2
$$

\
\
\
\

\
\
\
\

\
\
\
\

\
\
\
\

\thispagestyle{empty}

b.  Use the definition of derivatives to find $f'(x)$, and then find the tangent line to the graph of $y = f(x)$ at $x = 4$

$$
f(x) = \frac{4}{5x+1}
$$
\
\
\
\

\
\
\
\

\
\
\
\

\
\
\
\

\
\
\
\


\
\
\
\

\thispagestyle{empty}

c (Optional - 5 Points Extra Credits).  Use the definition of derivatives to find $f'(x)$.

$$
f(x) = x^5
$$

