---
title: "Exam 1 - Practice 2"
format: pdf
editor: visual
---

*Name:*

*Notice: Calculators are not allowed. *

---

## Some formulas:

- The derivative of $f(x)$ is defined by the formula:
$$
f'(x) = \lim_{h \to 0} \frac{f(x+h)-f(x)}{h}
$$
\


- An equation of the tangent line at $x = a$ is
$$
y - f(a) = f'(a)(x-a)
$$

---
### Problem 1.

Find the following limits.

$$\lim_{x \to 1} \frac{x^2 - 6x + 5}{x^2 -3x + 2}$$

\
\
\
\

$$\lim_{x \to 2024} \frac{x^2 - 6x + 5}{x^2 -3x + 2}$$

\
\
\
\
\


$$\lim_{x \to 0} \frac{2x^6 + 4x^2 + 3}{4x^6 +5x + 6}$$

\
\
\
\
\


$$\lim_{x \to \infty} \frac{2x^6 + 4x^2 + 3}{4x^6 +5x + 6}$$

\
\
\
\
\




$$\lim_{x \to \infty} \frac{2x^7 + 4x^2 + 3}{4x^6 +5x + 6}$$

\
\
\
\
\


$$\lim_{x \to \infty} \frac{2x^6 + 4x^9 + 3}{4x^7 + 5x + 6}$$

\
\
\
\
\


$$\lim_{x \to 1} \frac{\sin x }{\sin 7x}$$

\
\
\
\
\


$$\lim_{x \to 0} \frac{\sin 30x }{\sin 15x}$$

\
\
\
\
\


$$\lim_{x \to 0} \frac{x^3 + \sin 3x }{2x + 4\sin 5x}$$

\
\
\
\
\


### Problem 2

Find values of $x$, if any, at which the function is not continuous.

a.  $f(x) = 10x^2 + \frac{x-1}{3} + 2024$

\
\
\
\
\


b.  $f(x) = x^2 + \frac{3(x-2)}{(x - 1)(x-3)} + 2024$

\
\
\
\
\


c.  $f(x) = \frac{3}{2x + 5} + \frac{x-1}{x^2 - 8x + 12}$

\
\
\
\
\


### Problem 3.

Find a value of the constant $k$, if possible, that will make the function continuous everywhere.

a.  

    \begin{align*}
    f(x) =
     \left\{\begin{array}{lr}
       2x-2, & x \le 1 \\
       kx^2 + k, & x > 1  
    \end{array}\right.
    \end{align*}

\
\
\
\

\
\
\
\

b.  

    \begin{align*}
    f(x) =
     \left\{\begin{array}{lr}
       x^2 + x + 4, & x \le 3 \\
       x^2+ kx + k, & x > 3
    \end{array}\right.
    \end{align*}

\
\
\
\

\
\
\
\

### Problem 4.

a.  Use the definition of derivatives to find $f'(x)$, and then find the tangent line to the graph of $y = f(x)$ at $x = 1$

$$
f(x) = -2x^2 + 4x + 1
$$

\
\
\
\

\
\
\
\

\
\
\
\

\
\
\
\

b.  Use the definition of derivatives to find $f'(x)$, and then find the tangent line to the graph of $y = f(x)$ at $x = 0$

$$
f(x) = \frac{3}{2x+1}
$$

