---
title: "Final Exam - Math 121."
format: pdf
editor: visual
---

\thispagestyle{empty}


*Name:*

*Notice: Calculators are not allowed. *


---
### Problem 1. (5 points each)

Find the following limits.

$$\lim_{x \to 2} \frac{x^2 + 4x + 7}{x^2 +5x + 1}$$

\
\
\
\


\thispagestyle{empty}

$$\lim_{x \to 2} \frac{x^2 - 5x + 6}{x^2 -7x + 10}$$

\
\
\
\
\


$$\lim_{x \to \infty} \frac{2x^5 +4x^4 + 3x^3}{7x^5 + 2024}$$

\
\
\
\
\




$$\lim_{x \to \infty} \frac{-2x^8 +4x + 3}{3x^3 +5x + 6}$$

\
\
\
\
\


$$\lim_{x \to \infty} \frac{7x + 3}{x^3 +5x + 6}$$

\
\
\
\
\
\thispagestyle{empty}

$$\lim_{x \to 2} \frac{\sin x }{\sin 7x}$$

\
\
\
\
\


$$\lim_{x \to 0} \frac{\sin 10x }{\sin 5x}$$

\
\
\
\
\


$$\lim_{x \to 0} \frac{2x^2 + x+ \sin 3x }{3x^2 + 3\sin 5x}$$

\
\
\
\
\


### Problem 2 (5 points each)

Find values of $x$, if any, at which the function is not continuous.

a.  $f(x) = 3x^2 + \frac{x}{x-3} + 2024x +1$

\
\
\
\
\

\thispagestyle{empty}

b.  $f(x) = x^2 + \frac{3}{(x - 1)(x-2)(x-3)} + 2024$

\
\
\
\
\


c.  $f(x) = \frac{3}{x + 1} + \frac{x-1}{x^2 - 7x + 6}$

\
\
\
\
\


### Problem 3. (5 points each)

Find a value of the constant $k$, if possible, that will make the function continuous everywhere.

a.  

    \begin{align*}
    f(x) =
     \left\{\begin{array}{lr}
       x^2, & x \le 1 \\
       x^2 - 3kx+1, & x > 1  
    \end{array}\right.
    \end{align*}

\
\
\
\

\
\
\
\

\thispagestyle{empty}

b.  

    \begin{align*}
    f(x) =
     \left\{\begin{array}{lr}
       3x^2 + 4x + 1, & x \le 0 \\
      - 9x + k^2, & x > 0
    \end{array}\right.
    \end{align*}

\
\
\
\

\
\
\
\

\thispagestyle{empty}

### Problem 4. (17.5 points each)

a.  Use the definition of derivatives to find $f'(x)$, and then find the tangent line to the graph of $y = f(x)$ at $x = 3$

$$
f(x) = 5x^2 - 6x + 1
$$

\
\
\
\

\
\
\
\

\
\
\
\

\
\
\
\

\thispagestyle{empty}

b.  Use the definition of derivatives to find $f'(x)$, and then find the tangent line to the graph of $y = f(x)$ at $x = 4$

$$
f(x) = \frac{5}{3x+1}
$$
\
\
\
\

\
\
\
\

\
\
\
\

\
\
\
\

\
\
\
\


\
\
\
\

\thispagestyle{empty}

c (Optional - 5 Points Extra Credits).  Use the definition of derivatives to find $f'(x)$.

$$
f(x) = x^4
$$

\
\
\
\

\
\
\
\


\
\
\
\

### Problem 1.

*(5 points each)* Find $f'(x)$.

$$f(x) =  -\frac{2x}{3} + \frac{5x^2}{3} - \frac{1}{\sqrt[6]{x^3}} + \frac{1}{\sqrt{x}} + 2024x^2 + x + 2024$$

\
\
\
\

$$f(x) = (\sqrt{x}+1)(x^2+2x+1)$$

\
\
\
\
\

$$f(x) = \frac{x^3+1}{x^3-1} \text{   (Simplify your answers.)}$$

\
\thispagestyle{empty}


$$f(x) = 3x^2\cos x$$

\
\
\
\
\

$$f(x) = \frac{\sin x}{x}$$

\
\
\
\
\

$$f(x) = \sin \bigg(x + \sin x \bigg)$$

\
\
\
\
\

$$f(x) = \cos^{2}x$$

\
\
\
\
\

\thispagestyle{empty}



$$f(x) = \sin\bigg(x \cos x\bigg)$$



$$f(x) = \bigg(3\sin x - 2\cos x\bigg)^{2}$$

\
\
\
\
\

$$f(x) = e^x +17^x - 2\log_{3}x + 8\ln x - \frac{3\log_2 x}{2} + \frac{\log_9 x}{3} + 2024x + 1$$

\
\
\
\
\


$$f(x) = \log_{3}\bigg(\sqrt{x}+x^2+1\bigg)$$

\
\
\
\
\

\thispagestyle{empty}


$$f(x) = 100^{\cos x - \sin x + 3x^2}$$

\
\
\
\

$$f(x) = e^{x\cos x}$$


### Problem 2

*(8 points each)* 

$$
y + x^2y - x = 1
$$

(a) Find $dy/dx$ or $y'$ by differentiating implicitly.

\
\
\
\
\
\
\
\
\
\
\
\
\

(b) Solve the equation for y as a function of x, and find $dy/dx$ from that equation.

\thispagestyle{empty}

\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\

(c) Find an equation for the tangent line at the point (1, 1)

\

\thispagestyle{empty}

\
\
\
\
\
\
\
\
\
\
\
\
\

### Problem 3

*(5 points each)* 

(a) Find the local linear approximation of $f(x) = \sqrt[4]{x}$ at $x_0 = 1$\

\thispagestyle{empty}

\
\
\
\
\
\
\
\
\
\
\
\
\

(b) Use the local linear approximation obtained in part (a) to approximate $\sqrt[4]{1.1}$

\thispagestyle{empty}



### Problem 1.

Given that 

$$f(x) =  x^3 - 6x^2 + 9x + 1$$

Find all the intervals where

a. $f(x)$ is increasing
b. $f(x)$ is decreasing
c. $f(x)$ is concave upward
d. $f(x)$ is concave downward

\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\thispagestyle{empty}




### Problem 2

Find all the relative extrema of

$$
f(x) = 2x^3 -9x^2 + 12x + 1
$$

\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\thispagestyle{empty}

### Problem 3

Find an relative extrema of $f(x) = x^4 - x^2 - x + 1$ using gradient descent. 

\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\thispagestyle{empty}

### Problem 4

Find the absolute maximum and absolute minimum of $f(x) = 2x^3 - 15x^2 + 36x + 1$ on the interval [0, 1].

\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\thispagestyle{empty}


### Problem 5

The given equation has one (real) solution. Approximate the solution by Newton's method. 

$$x^3 + x - 1  = 0$$

