---
title: "Final Exam: Practice 2"
format: pdf
editor: visual
---

\thispagestyle{empty}


*Name:*

-   *Basic Calculators are allowed. Graphic calculators are not allowed.*
-   *A page of formula is allowed. Only formulas are allowed on the page. The page will be checked during the exam.*

---
### Problem 1

Use the definition of derivatives to find $f'(x)$, and then find the tangent line to the graph of $y = f(x)$ at $x = 1$

$$
f(x) = x^2  + 4x + 1
$$

{{< pagebreak >}}

### Problem 2

Find $f'(x)$.

$$f(x) =  \frac{x^8}{2} - \frac{4x^3}{7} - \frac{1}{\sqrt{x}} + \sqrt[3]{x} + 2024x + 1$$

\
\
\
\

$$f(x) = (\sqrt[4]{x}+1)(x+1)$$

\
\
\
\
\

$$f(x) = \frac{3x+2}{3x-2} \text{   (Simplify your answers.)}$$

\
\
\
\
\

\thispagestyle{empty}


$$f(x) = x^7\sin x$$

\
\
\
\
\

$$f(x) = \frac{x}{3\cos x}$$\
\
\
\
\

$$f(x) = \cos^{2024} x$$

\
\
\
\
\

$$f(x) = \cos(2x^4 + x^2 + 1)$$

\
\
\
\
\

\thispagestyle{empty}


$$f(x) = \cos\bigg(2\sin x + 3\cos x + x \bigg)$$

\
\
\
\
\

$$f(x) = \bigg(\cos x - \sin x\bigg)^{100}$$

\
\
\
\
\

$$f(x) = 4^x + 6^x - 7\log_{8}x + 9\ln x - \frac{3\log_2 x}{3} + \frac{\log_7 x}{2} + x + 1$$

\
\
\
\
\


$$f(x) = \ln\bigg(2x^2+3x+ \cos x\bigg)$$

\
\
\
\
\

\thispagestyle{empty}


$$f(x) = 3^{\sin x + \cos x}$$

\
\
\
\
\

$$f(x) = 3^{x^2\cos x}$$

\
\
\
\
\



### Problem 3

$$
y + x^4y + 3x^3 = 2
$$

(a) Find $dy/dx$ or $y'$ by differentiating implicitly.

\
\
\
\
\
\
\
\
\
\
\
\
\
\


(b) Solve the equation for y as a function of x, and find $dy/dx$ from that equation.

\thispagestyle{empty}

\
\
\
\
\
\
\
\
\
\
\
\
\
\

(c) Write an equation for the tangent line at the point (0, 2)\


{{< pagebreak >}}

### Problem 4

(a) Find the local linear approximation of $f(x) = e^x$ at $x_0 = 0$\. Notice that $e^0 = 1$

\thispagestyle{empty}

\
\
\
\
\
\
\
\
\
\
\

(b) Use the local linear approximation obtained in part (a) to approximate $e^{.01}$

{{< pagebreak >}}


### Problem 5

Given that 

$$f(x) =  x^3 + 6x^2 + 9x + 1$$

Find all the intervals where

a. $f(x)$ is increasing
b. $f(x)$ is decreasing
c. $f(x)$ is concave upward
d. $f(x)$ is concave downward

\thispagestyle{empty}

{{< pagebreak >}}


### Problem 6

Find all the relative extrema of

$$
f(x) = 2x^3 - 9x^2 + 12x + 2
$$

\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\thispagestyle{empty}



### Problem 7

Find the absolute maximum and absolute minimum of $f(x) = x^3 + 6x^2 +9x +1$ on the interval [-4, 4].


\thispagestyle{empty}
{{< pagebreak >}}

### Problem 8

The given equation has one (real) solution. Approximate the solution by Newton's method. 

$$x^3 + 5x + 2 = 0$$

\thispagestyle{empty}

```{r, echo=FALSE, eval=FALSE}

```


{{< pagebreak >}}


### Problem 9

Find the following 

$$\int \bigg(2x^4 - x^3 + 2x + 1 \bigg) dx$$

\
\
\
\
\
\
\
\
\
\

$$\int \bigg( \sqrt[5] x - 3x + \frac{2}{x}+ 1\bigg) dx$$
\thispagestyle{empty}

\
\
\
\
\
\
\
\
\
\

\thispagestyle{empty}

$$\int \bigg( 3^x + 2\sin x  - 3 \cos x + 3x + 1\bigg) dx$$

\
\
\
\
\
\
\
\
\
\


$$\int ( x^2  +x +1 )(x^2+2 ) dx$$

\
\
\
\
\
\
\
\

\thispagestyle{empty}

### Problem 10

Calculate the area between $f(x) = x^2 -7x + 6$ and x-axis bounded by $x = 1$ and $x = 10$

\thispagestyle{empty}